name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write
  deployments: write
  packages: write
  statuses: write
  issues: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Grant write access to pull request comments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - name: Install Integration Test Project
        run: cd test/integration/next-app && pnpm install

      - name: Build Integration Test Project
        run: cd test/integration/next-app && pnpm build

      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: '7'
          redis-port: 6379

      - name: Run tests
        run: pnpm test
        env:
          SKIP_BUILD: true

      - name: Code Coverage Comments
        uses: kcjpop/coverage-comments@v2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: './coverage/lcov.info'
      
      - name: Dry run the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for Semantic Release
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM token for publishing
        run: |
          npx semantic-release --dry-run

